# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Yinhai's Blog
tagline:             '千里之行，始于足下'
description:         '千里之行，始于足下'
url:                 'https://twitter.com/LiuYinhai'
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"


# About/contact
author:
name:              Liu Yinhai
url:               https://twitter.com/LiuYinhai
email:             yinhai.liu@gmail.com
twitter_username:  YinhaiLiu
github_username:   liuyinhai

# Custom vars
version:             1.0.0
