# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Yinhai's Blog
tagline:             '千里之行，始于足下'
description:         '千里之行，始于足下'
#url:                 'http://liuyinhai.github.com'
url:                 http://localhost:4000
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"


# About/contact
author:
    name:              Liu Yinhai
    email:             yinhai.liu@gmail.com

twitter_username:  YinhaiLiu
github_username:   liuyinhai

# Custom vars
version:             1.0.0
